#------------------
# General Variables
#------------------
variable "db_instance_id" {
  type        = string
  description = "ID of the DB instance. Used to determine the default log group name and build descriptive strings"
}

variable "db_instance_shortname" {
  type        = string
  description = "Short name for the DB instance. Used to build resource names and labels"
}

variable "alarm_actions_enabled" { 
  type        = bool
  default     = true
  description = "Determines whether SNS-based alarm actions are enabled when creating alarm resources"
}

variable "alarm_name_prefix" {
  type        = string
  default     = "RDS"
  description = "Prefix to apply to alarm names"
}

variable "alarm_topic_name" {
  type        = string
  default     = ""
  description = "The name of the SNS topic to use when alarm actions are enabled and email notifications are required"
}

variable "alarm_topic_name_ooh" {
  type        = string
  default     = ""
  description = "The name of the SNS topic to use when alarm actions are enabled and notifications are required OOH via xmatter"
}

variable "alert_log_group_name" {
  type        = string
  default     = ""
  description = "The full log group name for the Oracle alert logs if different from the AWS default as used for RDS"
}

#----------------------------------
# archiver Alarm & Filter Variables
#----------------------------------
variable "archiver_name_prefix" {
    type        = string
    default     = "Archiver is Stuck"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "archiver_description_prefix" {
    type        = string
    default     = "Alarms when an archiver becomes stuck"
    description = "Prefix used to form the Alarm description"
}

variable "archiver_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "archiver_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "archiver_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "archiver_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "archiver_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "archiver_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "archiver_filter_pattern" {
    type        = string
    default     = "\"ORA-00257\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "archiver_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "archiver_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "archiver_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#-----------------------------------
# bgprocess Alarm & Filter Variables
#-----------------------------------
variable "bgprocess_name_prefix" {
    type        = string
    default     = "Background Process Error"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "bgprocess_description_prefix" {
    type        = string
    default     = "Alarms when a background process is in error"
    description = "Prefix used to form the Alarm description"
}

variable "bgprocess_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "bgprocess_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "bgprocess_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "bgprocess_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "bgprocess_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "bgprocess_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "bgprocess_filter_pattern" {
    type        = string
    default     = "?\"ORA-00443\" ?\"ORA-00444\" ?\"ORA-00445\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "bgprocess_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "bgprocess_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "bgprocess_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#------------------------------------
# checkpoint Alarm & Filter Variables
#------------------------------------
variable "checkpoint_name_prefix" {
    type        = string
    default     = "Checkpoint Not Complete"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "checkpoint_description_prefix" {
    type        = string
    default     = "Alarms when a checkpoint fails to complete"
    description = "Prefix used to form the Alarm description"
}

variable "checkpoint_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "checkpoint_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "checkpoint_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "checkpoint_period" {
    type        = number
    default     = 300
    description = "The number of seconds for each evaluation period"
}

variable "checkpoint_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "checkpoint_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "checkpoint_filter_pattern" {
    type        = string
    default     = "\"Checkpoint not complete\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "checkpoint_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "checkpoint_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "checkpoint_alarm_ooh" {
    type        = bool
    default     = false
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#-------------------------------------
# controlfile Alarm & Filter Variables
#-------------------------------------
variable "controlfile_name_prefix" {
    type        = string
    default     = "Control File Error"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "controlfile_description_prefix" {
    type        = string
    default     = "Alarms when a control file is in error"
    description = "Prefix used to form the Alarm description"
}

variable "controlfile_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "controlfile_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "controlfile_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "controlfile_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "controlfile_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "controlfile_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "controlfile_filter_pattern" {
    type        = string
    default     = "?\"ORA-00204\" ?\"ORA-00206\" ?\"ORA-00210\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "controlfile_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "controlfile_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "controlfile_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#----------------------------------
# coredump Alarm & Filter Variables
#----------------------------------
variable "coredump_name_prefix" {
    type        = string
    default     = "Core Dump Generated"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "coredump_description_prefix" {
    type        = string
    default     = "Alarms when a core dump is generated"
    description = "Prefix used to form the Alarm description"
}

variable "coredump_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "coredump_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "coredump_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "coredump_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "coredump_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "coredump_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "coredump_filter_pattern" {
    type        = string
    default     = "\"ORA-07445\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "coredump_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "coredump_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "coredump_alarm_ooh" {
    type        = bool
    default     = false
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#-----------------------------------
# datablock Alarm & Filter Variables
#-----------------------------------
variable "datablock_name_prefix" {
    type        = string
    default     = "Data Block Corruption"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "datablock_description_prefix" {
    type        = string
    default     = "Alarms when data block corruption is detected"
    description = "Prefix used to form the Alarm description"
}

variable "datablock_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "datablock_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "datablock_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "datablock_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "datablock_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "datablock_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "datablock_filter_pattern" {
    type        = string
    default     = "\"ORA-01578\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "datablock_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "datablock_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "datablock_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#----------------------------------
# datafile Alarm & Filter Variables
#----------------------------------
variable "datafile_name_prefix" {
    type        = string
    default     = "Datafile Error"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "datafile_description_prefix" {
    type        = string
    default     = "Alarms when a datafile error occurs"
    description = "Prefix used to form the Alarm description"
}

variable "datafile_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "datafile_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "datafile_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "datafile_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "datafile_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "datafile_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "datafile_filter_pattern" {
    type        = string
    default     = "?\"ORA-01114\" ?\"ORA-01115\" ?\"ORA-01116\" ?\"ORA-01122\" ?\"ORA-01171\" ?\"ORA-01201\" ?\"ORA-01208\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "datafile_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "datafile_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "datafile_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#----------------------------------
# rollback Alarm & Filter Variables
#----------------------------------
variable "rollback_name_prefix" {
    type        = string
    default     = "Failed to Extend Rollback Segment"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "rollback_description_prefix" {
    type        = string
    default     = "Alarms when extending the rollback segment fails"
    description = "Prefix used to form the Alarm description"
}

variable "rollback_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "rollback_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "rollback_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "rollback_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "rollback_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "rollback_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "rollback_filter_pattern" {
    type        = string
    default     = "\"ORA-01562\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "rollback_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "rollback_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "rollback_alarm_ooh" {
    type        = bool
    default     = false
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#------------------------------------
# backupfail Alarm & Filter Variables
#------------------------------------
variable "backupfail_name_prefix" {
    type        = string
    default     = "Backup Failure - No Space on Device"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "backupfail_description_prefix" {
    type        = string
    default     = "Alarms when a backup has failed due to insifficient space on the DB block device"
    description = "Prefix used to form the Alarm description"
}

variable "backupfail_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "backupfail_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "backupfail_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "backupfail_period" {
    type        = number
    default     = 300
    description = "The number of seconds for each evaluation period"
}

variable "backupfail_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "backupfail_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "backupfail_filter_pattern" {
    type        = string
    default     = "\"ORA-27063\" ?\"ORA-19502\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "backupfail_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "backupfail_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "backupfail_alarm_ooh" {
    type        = bool
    default     = false
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#----------------------------------
# ora00600 Alarm & Filter Variables
#----------------------------------
variable "ora00600_name_prefix" {
    type        = string
    default     = "ORA-00600 Error"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "ora00600_description_prefix" {
    type        = string
    default     = "Alarms when an ORA-00600 error is generated"
    description = "Prefix used to form the Alarm description"
}

variable "ora00600_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "ora00600_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "ora00600_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "ora00600_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "ora00600_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "ora00600_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "ora00600_filter_pattern" {
    type        = string
    default     = "\"ORA-00600\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "ora00600_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "ora00600_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "ora00600_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#-----------------------------------
# sharedmem Alarm & Filter Variables
#-----------------------------------
variable "sharedmem_name_prefix" {
    type        = string
    default     = "Out of Shared Memory"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "sharedmem_description_prefix" {
    type        = string
    default     = "Alarms when shared memory is exhausted"
    description = "Prefix used to form the Alarm description"
}

variable "sharedmem_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "sharedmem_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "sharedmem_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "sharedmem_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "sharedmem_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "sharedmem_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "sharedmem_filter_pattern" {
    type        = string
    default     = "\"ORA-04031\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "sharedmem_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "sharedmem_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "sharedmem_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#---------------------------------
# redolog Alarm & Filter Variables
#---------------------------------
variable "redolog_name_prefix" {
    type        = string
    default     = "Redo Log File Error"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "redolog_description_prefix" {
    type        = string
    default     = "Alarms when a redo log file error occurs"
    description = "Prefix used to form the Alarm description"
}

variable "redolog_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "redolog_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "redolog_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "redolog_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "redolog_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "redolog_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "redolog_filter_pattern" {
    type        = string
    default     = "?\"ORA-00333\" ?\"ORA-00345\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "redolog_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "redolog_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "redolog_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#----------------------------------
# snapshot Alarm & Filter Variables
#----------------------------------
variable "snapshot_name_prefix" {
    type        = string
    default     = "Snapshot Too Old"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "snapshot_description_prefix" {
    type        = string
    default     = "Alarms when a snapshot is determined to be too old"
    description = "Prefix used to form the Alarm description"
}

variable "snapshot_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "snapshot_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "snapshot_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "snapshot_period" {
    type        = number
    default     = 300
    description = "The number of seconds for each evaluation period"
}

variable "snapshot_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "snapshot_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "snapshot_filter_pattern" {
    type        = string
    default     = "\"ORA-01555\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "snapshot_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "snapshot_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "snapshot_alarm_ooh" {
    type        = bool
    default     = false
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#--------------------------------
# extend Alarm & Filter Variables
#--------------------------------
variable "extend_name_prefix" {
    type        = string
    default     = "Unable to Extend"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "extend_description_prefix" {
    type        = string
    default     = "Alarms when a general Unable to Extend error occurs"
    description = "Prefix used to form the Alarm description"
}

variable "extend_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "extend_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "extend_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "extend_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "extend_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "extend_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "extend_filter_pattern" {
    type        = string
    default     = "\"unable to extend\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "extend_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "extend_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "extend_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#-----------------------------------
# extendlob Alarm & Filter Variables
#-----------------------------------
variable "extendlob_name_prefix" {
    type        = string
    default     = "Unable to Extend LOBSEGMENT"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "extendlob_description_prefix" {
    type        = string
    default     = "Alarms when LOBSEGMENT cannot be extended"
    description = "Prefix used to form the Alarm description"
}

variable "extendlob_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "extendlob_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "extendlob_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "extendlob_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "extendlob_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "extendlob_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "extendlob_filter_pattern" {
    type        = string
    default     = "\"ORA-01691\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "extendlob_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "extendlob_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "extendlob_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#-------------------------------------
# extendtable Alarm & Filter Variables
#-------------------------------------
variable "extendtable_name_prefix" {
    type        = string
    default     = "Unable to Extend Tablespace"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "extendtable_description_prefix" {
    type        = string
    default     = "Alarms when tablespace cannot be extended"
    description = "Prefix used to form the Alarm description"
}

variable "extendtable_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "extendtable_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "extendtable_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "extendtable_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "extendtable_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "extendtable_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "extendtable_filter_pattern" {
    type        = string
    default     = "\"ORA-01653\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "extendtable_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "extendtable_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "extendtable_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#------------------------------------
# extendtemp Alarm & Filter Variables
#------------------------------------
variable "extendtemp_name_prefix" {
    type        = string
    default     = "Unable to Extend Temp Segment"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "extendtemp_description_prefix" {
    type        = string
    default     = "Alarms when the temp segment cannot be extended"
    description = "Prefix used to form the Alarm description"
}

variable "extendtemp_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "extendtemp_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "extendtemp_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "extendtemp_period" {
    type        = number
    default     = 60
    description = "The number of seconds for each evaluation period"
}

variable "extendtemp_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "extendtemp_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "extendtemp_filter_pattern" {
    type        = string
    default     = "\"ORA-01652\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "extendtemp_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "extendtemp_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "extendtemp_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

#------------------------------------
# orastreams Alarm & Filter Variables
#------------------------------------
variable "orastreams_name_prefix" {
    type        = string
    default     = "Oracle Streams Error"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "orastreams_description_prefix" {
    type        = string
    default     = "Alarms when an Oracle Streams error occurs"
    description = "Prefix used to form the Alarm description"
}

variable "orastreams_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "orastreams_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "orastreams_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "orastreams_period" {
    type        = number
    default     = 300
    description = "The number of seconds for each evaluation period"
}

variable "orastreams_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "orastreams_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "orastreams_filter_pattern" {
    type        = string
    default     = "\"STREAMS\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "orastreams_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "orastreams_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "orastreams_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}

variable "orastreams_alarm_enable" {
    type        = bool
    default     = false
    description = "Defines whether the alarm should be created (true) or not (false)"
}

#--------------------------------------
# cantaddfiles Alarm & Filter Variables
#--------------------------------------
variable "cantaddfiles_name_prefix" {
    type        = string
    default     = "Cannot Add Files - No Space on Device"
    description = "Prefix used to form the name of the Alarm and Log Filter"
}

variable "cantaddfiles_description_prefix" {
    type        = string
    default     = "Alarms when there is no space left on the DB block device to add new files"
    description = "Prefix used to form the Alarm description"
}

variable "cantaddfiles_comparison_operator" {
    type        = string
    default     = "GreaterThanOrEqualToThreshold"
    description = "The comparison operator used to evaluate the alarm health against the threshold"
}

variable "cantaddfiles_datapoints_to_alarm" {
    type        = number
    default     = 1
    description = "The number of datapoints to evaluate when determining alarm state"
}

variable "cantaddfiles_evaluation_periods" {
    type        = number
    default     = 1
    description = "The number of evaluation periods used when determining alarm state"
}

variable "cantaddfiles_period" {
    type        = number
    default     = 300
    description = "The number of seconds for each evaluation period"
}

variable "cantaddfiles_statistic" {
    type        = string
    default     = "Sum"
    description = "The statistic to apply to the metric"
}

variable "cantaddfiles_threshold" {
    type        = number
    default     = 1
    description = "The value that the statistic is compared against to determine alarm state"
}

variable "cantaddfiles_filter_pattern" {
    type        = string
    default     = "\"ORA-01118\""
    description = "Filter expression used to extract metric data from ingested logs"
}

variable "cantaddfiles_filter_metric_value" {
    type        = number
    default     = 1
    description = "Data published to the metric when the filter pattern matches"
}

variable "cantaddfiles_filter_metric_default_value" {
    type        = number
    default     = 0
    description = "Data published to the metric when the filter pattern does not match"
}

variable "cantaddfiles_alarm_ooh" {
    type        = bool
    default     = true
    description = "Defines whether alarms generated by this metric filter should additionally notify OOH via xmatter (true) or not (false)"
}
